using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Robogame.Tools.Editor
{
    /// <summary>
    /// "Continual Traces" — durable code↔decision breadcrumbs. A trace is an
    /// inline marker <c>// TRACE[id]: note</c> that anchors a line of code to a
    /// decision / rule / finding / log it depends on, so the rationale stays
    /// discoverable and the link rots loudly instead of silently.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Syntax.</b> <c>// TRACE[id]: free-text note</c>. Recognised id kinds:
    /// </para>
    /// <list type="bullet">
    ///   <item><c>ADR-NNNN</c> → <c>docs/decisions/NNNN-*.md</c></item>
    ///   <item><c>INV-N</c> → <c>docs/invariants.md</c> § N heading</item>
    ///   <item><c>AUDIT-N</c> → finding N in <c>docs/changes/109-*.md</c></item>
    ///   <item><c>LOG-NN</c> → session log <c>docs/changes/NN-*.md</c></item>
    ///   <item><c>DOC:name[§sec]</c> → a file named <c>name</c> under <c>docs/</c></item>
    /// </list>
    /// <para>
    /// <b>Tools.</b> <c>Robogame/Traces/Validate</c> reports dangling traces in
    /// the console; <c>Robogame/Traces/Rebuild Index</c> regenerates
    /// <c>docs/TRACES.md</c> (target → code sites). Both are manual and
    /// non-blocking, matching the other scaffolders. Convention recorded in
    /// <c>CLAUDE.md</c>.
    /// </para>
    /// </remarks>
    public static class ContinualTraces
    {
        // // TRACE[ <id> ] : <note>   — id is non-greedy up to the first ']'.
        private static readonly Regex s_marker = new Regex(
            @"//\s*TRACE\[\s*(?<id>[^\]]+?)\s*\]\s*:?\s*(?<note>.*)$",
            RegexOptions.Compiled);

        private const string IndexPath = "docs/TRACES.md";

        private readonly struct Trace
        {
            public readonly string Id;
            public readonly string Note;
            public readonly string RelFile; // project-relative, forward slashes
            public readonly int Line;

            public Trace(string id, string note, string relFile, int line)
            {
                Id = id; Note = note; RelFile = relFile; Line = line;
            }
        }

        // -----------------------------------------------------------------
        // Menu entries
        // -----------------------------------------------------------------

        [MenuItem("Robogame/Traces/Validate", priority = 300)]
        public static void Validate()
        {
            string root = ProjectRoot();
            List<Trace> traces = Scan(root);
            int ok = 0;
            var sb = new StringBuilder();
            foreach (Trace t in traces)
            {
                if (Resolve(root, t.Id, out string reason)) { ok++; continue; }
                sb.AppendLine($"  ✗ {t.RelFile}:{t.Line}  TRACE[{t.Id}] — {reason}");
            }

            int dangling = traces.Count - ok;
            string head = $"[Traces] {traces.Count} traces, {ok} resolve, {dangling} dangling.";
            if (dangling == 0) Debug.Log(head + " ✓");
            else Debug.LogWarning(head + "\n" + sb);
        }

        [MenuItem("Robogame/Traces/Rebuild Index", priority = 301)]
        public static void RebuildIndex()
        {
            string root = ProjectRoot();
            List<Trace> traces = Scan(root);

            // Group by id; within a group, stable by file:line.
            var groups = traces
                .GroupBy(t => t.Id)
                .OrderBy(g => g.Key, StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("# Continual Traces — index");
            sb.AppendLine();
            sb.AppendLine("> Generated by **Robogame → Traces → Rebuild Index**. Do not edit by hand.");
            sb.AppendLine("> Each entry is a decision/rule/finding anchor and the code lines that cite it.");
            sb.AppendLine("> Syntax: `// TRACE[id]: note` — see `ContinualTraces.cs` / `CLAUDE.md`.");
            sb.AppendLine();

            int dangling = 0;
            foreach (var g in groups)
            {
                bool resolved = Resolve(root, g.Key, out string reason);
                if (!resolved) dangling++;
                string flag = resolved ? "" : $"  ⚠️ DANGLING — {reason}";
                sb.AppendLine($"## {g.Key}{flag}");
                foreach (Trace t in g.OrderBy(x => x.RelFile, StringComparer.Ordinal).ThenBy(x => x.Line))
                {
                    string note = string.IsNullOrWhiteSpace(t.Note) ? "" : $" — {t.Note.Trim()}";
                    sb.AppendLine($"- `{t.RelFile}:{t.Line}`{note}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine($"_{traces.Count} traces across {traces.Select(t => t.RelFile).Distinct().Count()} files; " +
                          $"{groups.Count()} anchors, {dangling} dangling._");

            string outPath = Path.Combine(root, IndexPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outPath));
            File.WriteAllText(outPath, sb.ToString());
            Debug.Log($"[Traces] Wrote {IndexPath} — {traces.Count} traces, {dangling} dangling.");
            AssetDatabase.Refresh();
        }

        // -----------------------------------------------------------------
        // Scan
        // -----------------------------------------------------------------

        private static List<Trace> Scan(string root)
        {
            var traces = new List<Trace>();
            string assets = Application.dataPath; // <root>/Assets
            foreach (string path in Directory.EnumerateFiles(assets, "*.cs", SearchOption.AllDirectories))
            {
                // Self-exclusion: this file's inline `//` syntax examples
                // (`TRACE[<id>]`, the index header literal) match the marker
                // regex and reported as 2 permanently-dangling traces.
                if (Path.GetFileName(path) == "ContinualTraces.cs") continue;
                string[] lines = File.ReadAllLines(path);
                string rel = path.Substring(root.Length).TrimStart('/', '\\').Replace('\\', '/');
                for (int i = 0; i < lines.Length; i++)
                {
                    // Traces are inline `//` comments. Skip `///` XML-doc lines
                    // and `*` block-comment bodies so this file's own syntax
                    // examples (and other doc prose) aren't picked up as traces.
                    string trimmed = lines[i].TrimStart();
                    if (trimmed.StartsWith("///") || trimmed.StartsWith("*")) continue;
                    Match m = s_marker.Match(lines[i]);
                    if (!m.Success) continue;
                    traces.Add(new Trace(m.Groups["id"].Value, m.Groups["note"].Value, rel, i + 1));
                }
            }
            return traces;
        }

        // -----------------------------------------------------------------
        // Resolution
        // -----------------------------------------------------------------

        private static bool Resolve(string root, string id, out string reason)
        {
            reason = null;
            string docs = Path.Combine(root, "docs");

            Match adr = Regex.Match(id, @"^ADR-(\d+)$");
            if (adr.Success)
            {
                string num = adr.Groups[1].Value.PadLeft(4, '0');
                if (DocsGlob(Path.Combine(docs, "decisions"), num + "-*.md").Any()) return true;
                reason = $"no docs/decisions/{num}-*.md"; return false;
            }

            Match inv = Regex.Match(id, @"^INV-(\d+)$");
            if (inv.Success)
            {
                string file = Path.Combine(docs, "invariants.md");
                if (!File.Exists(file)) { reason = "docs/invariants.md missing"; return false; }
                if (Regex.IsMatch(File.ReadAllText(file), $@"(?m)^##\s*{inv.Groups[1].Value}\.")) return true;
                reason = $"no '## {inv.Groups[1].Value}.' heading in invariants.md"; return false;
            }

            Match audit = Regex.Match(id, @"^AUDIT-(\d+)$");
            if (audit.Success)
            {
                string file = DocsGlob(Path.Combine(docs, "changes"), "109-*.md").FirstOrDefault();
                if (file == null) { reason = "no docs/changes/109-*.md"; return false; }
                if (Regex.IsMatch(File.ReadAllText(file), $@"(?m)^{audit.Groups[1].Value}\.\s")) return true;
                reason = $"no finding {audit.Groups[1].Value} in 109 audit"; return false;
            }

            Match log = Regex.Match(id, @"^LOG-(\d+)$");
            if (log.Success)
            {
                if (DocsGlob(Path.Combine(docs, "changes"), log.Groups[1].Value + "-*.md").Any()) return true;
                reason = $"no session log docs/changes/{log.Groups[1].Value}-*.md"; return false;
            }

            if (id.StartsWith("DOC:", StringComparison.Ordinal))
            {
                string name = id.Substring(4).Split('§', '#')[0].Trim();
                if (name.Length == 0) { reason = "empty DOC name"; return false; }
                // Forgiving resolution — sites author ids in three shapes
                // that the strict filename match reported as dangling even
                // though every target exists (LOG-157 traces repair):
                //  1. no extension ("best-practices§…") → append .md;
                //  2. docs-relative path ("research/ui-design-handoff");
                //  3. repo-root docs ("CLAUDE.md§…") — CLAUDE.md lives
                //     outside docs/ by convention.
                if (!name.EndsWith(".md", StringComparison.OrdinalIgnoreCase)) name += ".md";
                bool hasPath = name.IndexOf('/') >= 0 || name.IndexOf('\\') >= 0;
                if (hasPath)
                {
                    if (File.Exists(Path.Combine(docs, name))) return true;
                }
                else
                {
                    if (Directory.Exists(docs) &&
                        Directory.EnumerateFiles(docs, name, SearchOption.AllDirectories).Any()) return true;
                    if (File.Exists(Path.Combine(ProjectRoot(), name))) return true;
                }
                reason = $"no doc '{name}' under docs/ (or repo root)"; return false;
            }

            reason = "unrecognised id kind (expected ADR-/INV-/AUDIT-/LOG-/DOC:)";
            return false;
        }

        private static IEnumerable<string> DocsGlob(string dir, string pattern) =>
            Directory.Exists(dir)
                ? Directory.EnumerateFiles(dir, pattern, SearchOption.TopDirectoryOnly)
                : Enumerable.Empty<string>();

        private static string ProjectRoot() =>
            Directory.GetParent(Application.dataPath)!.FullName;
    }
}
