using System.IO;
using NUnit.Framework;
using Robogame.Block;
using UnityEditor;
using UnityEngine;

namespace Robogame.Tests.EditMode.Blueprints
{
    /// <summary>
    /// Loads every shipped preset blueprint asset off disk and validates
    /// it. Run via Window → Test Runner → EditMode. Catches "the
    /// scaffolder authored a chassis that fails CPU connectivity" before
    /// the user notices it in-game.
    /// </summary>
    /// <remarks>
    /// Also writes ASCII dumps to <c>docs/blueprint-snapshots/</c> so the
    /// human reviewer can read what each preset looks like without
    /// opening Unity. The dump file is NOT a test fixture — it's an
    /// observable output for manual review.
    /// </remarks>
    public sealed class PresetBlueprintTests
    {
        private const string BlueprintFolder = "Assets/_Project/ScriptableObjects/Blueprints";

        // Repo-relative path for the snapshot file. Unity's Application.dataPath
        // ends in "/Assets" — go up one level to reach the project root.
        private static string SnapshotPath
            => Path.Combine(Path.GetDirectoryName(Application.dataPath) ?? "", "docs", "blueprint-snapshots", "presets.md");

        // Every preset asset path the scaffolder produces. Add new entries
        // here when GameplayScaffolder ships a new blueprint preset.
        private static string[] PresetPaths => new[]
        {
            BlueprintFolder + "/Blueprint_DefaultGround.asset",
            BlueprintFolder + "/Blueprint_DefaultPlane.asset",
            BlueprintFolder + "/Blueprint_DefaultBuggy.asset",
            BlueprintFolder + "/Blueprint_DefaultBoat.asset",
            BlueprintFolder + "/Blueprint_DefaultBomber.asset",
            BlueprintFolder + "/Blueprint_DefaultHelicopter.asset",
            BlueprintFolder + "/Blueprint_CombatDummy.asset",
            BlueprintFolder + "/Blueprint_StressRotorTower.asset",
        };

        [TestCaseSource(nameof(PresetPaths))]
        public void Preset_PassesValidation(string assetPath)
        {
            ChassisBlueprint bp = AssetDatabase.LoadAssetAtPath<ChassisBlueprint>(assetPath);
            if (bp == null)
            {
                Assert.Inconclusive($"Preset asset not found at {assetPath}. Run Robogame → Build Everything to scaffold.");
                return;
            }

            BlueprintPlan plan = new BlueprintPlan(bp.DisplayName, bp.Kind, bp.Entries, bp.RotorsGenerateLift);
            BlueprintValidationResult r = BlueprintValidator.Validate(plan);
            Assert.IsTrue(r.IsValid, $"Validation failed for {bp.DisplayName}:\n{r}");
        }

        /// <summary>
        /// Generates a markdown snapshot of every preset's ASCII layout
        /// to <c>docs/blueprint-snapshots/presets.md</c>. Re-runs every
        /// time the test runs; check the diff into git after iteration
        /// passes so the blueprint shapes are visible in code review.
        /// </summary>
        [Test]
        public void DumpAllPresets_WritesAsciiSnapshot()
        {
            string dir = Path.GetDirectoryName(SnapshotPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            using (StreamWriter w = new StreamWriter(SnapshotPath, false))
            {
                w.WriteLine("# Blueprint snapshots");
                w.WriteLine();
                w.WriteLine("Auto-generated by `PresetBlueprintTests.DumpAllPresets_WritesAsciiSnapshot`.");
                w.WriteLine("Run Window → Test Runner → EditMode → DumpAllPresets to refresh.");
                w.WriteLine();
                int loaded = 0;
                foreach (string path in PresetPaths)
                {
                    ChassisBlueprint bp = AssetDatabase.LoadAssetAtPath<ChassisBlueprint>(path);
                    if (bp == null)
                    {
                        w.WriteLine($"## (missing: {path})");
                        w.WriteLine();
                        continue;
                    }
                    loaded++;
                    BlueprintPlan plan = new BlueprintPlan(bp.DisplayName, bp.Kind, bp.Entries, bp.RotorsGenerateLift);
                    BlueprintValidationResult r = BlueprintValidator.Validate(plan);
                    w.WriteLine("## " + bp.DisplayName);
                    w.WriteLine();
                    w.WriteLine("```");
                    w.Write(BlueprintAsciiDump.Dump(plan));
                    w.WriteLine("```");
                    w.WriteLine();
                    w.WriteLine("Validation: " + (r.IsValid ? "OK" : "FAILED"));
                    if (r.Errors.Count > 0 || r.Warnings.Count > 0)
                    {
                        w.WriteLine();
                        w.WriteLine("```");
                        w.Write(r.ToString());
                        w.WriteLine();
                        w.WriteLine("```");
                    }
                    w.WriteLine();
                }
                if (loaded == 0)
                    Assert.Inconclusive("No preset assets found. Scaffold first.");
            }
            UnityEngine.Debug.Log($"[PresetBlueprintTests] Wrote snapshot to {SnapshotPath}");
        }
    }
}
